### ISSUE TITLE
about 10X genomics data 

### ISSUE THREAD

**Issue by komais** [phoenixding/tbsp#1]
do you have any suggestion on  10x genomic data ?  whether it is too short to call SNP and not suitable for tbsp?

**Comment by phoenixding** [comment]
@komais 
This is a great question.  In general, it's more difficult to get the SNP candidates from 10x genomic data as it only covers a small portion of genome.  The TBSP method is based on those identified SNP candidates and thus also limited. 

A rotation student in our group has applied TBSP to study one single-cell umi data in liver development (https://www.ncbi.nlm.nih.gov/pubmed/28166538). 
She used GATK RNA-seq pipeline (https://gatkforums.broadinstitute.org/gatk/discussion/3892/the-gatk-best-practices-for-variant-calling-on-rnaseq-in-full-detail) to call the SNP candidates and it turns out that only very limited SNP candidates (<20) can be found.  It significantly limits the following TBSP analysis. 

We found that the GATK pipeline might be too stringent to call SNP candidates in umi data. 
We also tried freebayes pipeline using the default parameters, indeed we got much more SNP candidates ( a few hundreds) using the freebayes.  The TBSP results are also better compared with the GATK pipeline based. 

But, even a few hundreds SNP candidates are still significantly fewer than the SNP candidates we usually got from the full-length RNA-seq (e.g. ~3k for this data https://www.ncbi.nlm.nih.gov/pubmed/27281220 by GATK). 

To answer your question:
Yes, TBSP is better suited for the full-length RNA-seq as it captures more potential mutations.
For the umi-based RNA-seq such as 10x genomic data,  TBSP can still predict some SNPs, which are informative for the trajectory inference, especially using less-stringent SNP calling pipelines.  But it's not recommended reconstructing the trajectory based on only the SNPs in the umi data. 
We can try to improve the expression-based trajectories using the identified SNPs. 
Here is a naive way to integrate SNP with expression: https://github.com/phoenixding/tbsp#integration-with-existing-methods.
