### ISSUE TITLE
Script of bam2vcf.py

### ISSUE THREAD

**Issue by AidenSb** [phoenixding/tbsp#5]
Dear Ding,
Thanks for the package. I couldn't find the bam2vcf.py script. and it apparently has been deleted from the cloud. would you please provide it again?

Thanks
Aiden

**Comment by phoenixding** [comment]
@AidenSb 
Thanks for reporting this issue.
For some unknown reasons, the old link expired. Please use this one instead:
https://my.pcloud.com/publink/show?code=XZH5iFkZz0uXbbvQ8AQznXWoRXBOS0VJUtuV

I have already fixed the github page. Let me know if you have any other questions. THanks

**Comment by AidenSb** [comment]
Thanks a lot, it works now.
Another question, can we give the scRNAseq output bam file as input to this? or I should split the bam file for each cell first and give bam file of each cell as input?

**Comment by phoenixding** [comment]
@AidenSb 
Great question! Unfortunately, it does not support bar-coded bam for now (e.g., the direct output from 10x cell ranger software). You have to somehow separate the cells into individual bam files in order to use it.  I believe that you can find instructions about how to separate the cells from 10x genomics website (suppose you are using 10x platform). For other single-cell RNA-seq datasets, you should be able to do so with a similar strategy (usually by filtering the tag in the bam file).

**Comment by AidenSb** [comment]
Hi Ding,
would you please let me know how you dealt with the splitting of a BAM file, to get cell-specific bam files? would you please share your code for it?

Thanks

**Comment by phoenixding** [comment]
@AidenSb 
10x genomics has a script for it.  It's designed for 10x genomcis data. But It should be working for other bar-coded bam too (as long as it has the cell id as the CB tag)
https://github.com/10XGenomics/subset-bam

Also, a script here：
https://github.com/brentp/hts-nim-tools/issues/5
and here:
https://bioinformatics.stackexchange.com/questions/12868/is-there-a-command-line-tool-to-split-a-sam-bam-file-by-cb-cell-barcode-tag/12869

**Comment by AidenSb** [comment]
Thanks a lot Ding.
